tables:
  bqrtsv:
    description: 'Base quality recalibration metrics.'
    pattern: "\\.sage\\.bqr\\.tsv$"
    ftype: 'txt'
    columns:
      - raw: 'alt'
        tidy: 'alt'
        type: 'char'
        description: 'alternate allele'
        versions: ['v3.4.4', 'latest']
      - raw: 'ref'
        tidy: 'ref'
        type: 'char'
        description: 'reference allele'
        versions: ['v3.4.4', 'latest']
      - raw: 'trinucleotideContext'
        tidy: 'context'
        type: 'char'
        description: 'trinucleotide context'
        versions: ['v3.4.4', 'latest']
      - raw: 'readType'
        tidy: 'read_type'
        type: 'char'
        description: 'read type'
        versions: ['latest']
      - raw: 'count'
        tidy: 'count'
        type: 'float'
        description: 'count'
        versions: ['v3.4.4', 'latest']
      - raw: 'originalQual'
        tidy: 'origq'
        type: 'float'
        description: 'original quality'
        versions: ['v3.4.4', 'latest']
      - raw: 'recalibratedQual'
        tidy: 'recalq'
        type: 'float'
        description: 'recalibrated quality'
        versions: ['v3.4.4', 'latest']
  genecvg:
    description: 'Gene coverage metrics.'
    pattern: "\\.sage\\.gene\\.coverage\\.tsv$"
    ftype: 'txt'
    columns:
      - raw: 'gene'
        tidy: 'gene'
        type: 'char'
        description: 'gene name'
        versions: ['latest']
      - raw: 'chromosome'
        tidy: 'chrom'
        type: 'char'
        description: 'chromosome'
        versions: ['latest']
      - raw: 'posStart'
        tidy: 'pos_start'
        type: 'float'
        description: 'start position'
        versions: ['latest']
      - raw: 'posEnd'
        tidy: 'pos_end'
        type: 'float'
        description: 'end position'
        versions: ['latest']
      - raw: 'missedVariantLikelihood'
        tidy: 'missed_var_likelihood'
        type: 'float'
        description: 'missed variant likelihood'
        versions: ['latest']
      - raw: 'DR_0'
        tidy: 'dr_0'
        type: 'float'
        description: 'depth range 0'
        versions: ['latest']
      - raw: 'DR_1'
        tidy: 'dr_1'
        type: 'float'
        description: 'depth range 1'
        versions: ['latest']
      - raw: 'DR_2'
        tidy: 'dr_2'
        type: 'float'
        description: 'depth range 2'
        versions: ['latest']
      - raw: 'DR_3'
        tidy: 'dr_3'
        type: 'float'
        description: 'depth range 3'
        versions: ['latest']
      - raw: 'DR_4'
        tidy: 'dr_4'
        type: 'float'
        description: 'depth range 4'
        versions: ['latest']
      - raw: 'DR_5'
        tidy: 'dr_5'
        type: 'float'
        description: 'depth range 5'
        versions: ['latest']
      - raw: 'DR_6'
        tidy: 'dr_6'
        type: 'float'
        description: 'depth range 6'
        versions: ['latest']
      - raw: 'DR_7'
        tidy: 'dr_7'
        type: 'float'
        description: 'depth range 7'
        versions: ['latest']
      - raw: 'DR_8'
        tidy: 'dr_8'
        type: 'float'
        description: 'depth range 8'
        versions: ['latest']
      - raw: 'DR_9'
        tidy: 'dr_9'
        type: 'float'
        description: 'depth range 9'
        versions: ['latest']
      - raw: 'DR_10'
        tidy: 'dr_10'
        type: 'float'
        description: 'depth range 10'
        versions: ['latest']
      - raw: 'DR_11'
        tidy: 'dr_11'
        type: 'float'
        description: 'depth range 11'
        versions: ['latest']
      - raw: 'DR_12'
        tidy: 'dr_12'
        type: 'float'
        description: 'depth range 12'
        versions: ['latest']
      - raw: 'DR_13'
        tidy: 'dr_13'
        type: 'float'
        description: 'depth range 13'
        versions: ['latest']
      - raw: 'DR_14'
        tidy: 'dr_14'
        type: 'float'
        description: 'depth range 14'
        versions: ['latest']
      - raw: 'DR_15'
        tidy: 'dr_15'
        type: 'float'
        description: 'depth range 15'
        versions: ['latest']
      - raw: 'DR_16'
        tidy: 'dr_16'
        type: 'float'
        description: 'depth range 16'
        versions: ['latest']
      - raw: 'DR_17'
        tidy: 'dr_17'
        type: 'float'
        description: 'depth range 17'
        versions: ['latest']
      - raw: 'DR_18'
        tidy: 'dr_18'
        type: 'float'
        description: 'depth range 18'
        versions: ['latest']
      - raw: 'DR_19'
        tidy: 'dr_19'
        type: 'float'
        description: 'depth range 19'
        versions: ['latest']
      - raw: 'DR_20'
        tidy: 'dr_20'
        type: 'float'
        description: 'depth range 20'
        versions: ['latest']
      - raw: 'DR_21'
        tidy: 'dr_21'
        type: 'float'
        description: 'depth range 21'
        versions: ['latest']
      - raw: 'DR_22'
        tidy: 'dr_22'
        type: 'float'
        description: 'depth range 22'
        versions: ['latest']
      - raw: 'DR_23'
        tidy: 'dr_23'
        type: 'float'
        description: 'depth range 23'
        versions: ['latest']
      - raw: 'DR_24'
        tidy: 'dr_24'
        type: 'float'
        description: 'depth range 24'
        versions: ['latest']
      - raw: 'DR_25'
        tidy: 'dr_25'
        type: 'float'
        description: 'depth range 25'
        versions: ['latest']
      - raw: 'DR_26'
        tidy: 'dr_26'
        type: 'float'
        description: 'depth range 26'
        versions: ['latest']
      - raw: 'DR_27'
        tidy: 'dr_27'
        type: 'float'
        description: 'depth range 27'
        versions: ['latest']
      - raw: 'DR_28'
        tidy: 'dr_28'
        type: 'float'
        description: 'depth range 28'
        versions: ['latest']
      - raw: 'DR_29'
        tidy: 'dr_29'
        type: 'float'
        description: 'depth range 29'
        versions: ['latest']
      - raw: 'DR_30_39'
        tidy: 'dr_30_39'
        type: 'float'
        description: 'depth range 30-39'
        versions: ['latest']
      - raw: 'DR_40_49'
        tidy: 'dr_40_49'
        type: 'float'
        description: 'depth range 40-49'
        versions: ['latest']
      - raw: 'DR_50_59'
        tidy: 'dr_50_59'
        type: 'float'
        description: 'depth range 50-59'
        versions: ['latest']
      - raw: 'DR_60_69'
        tidy: 'dr_60_69'
        type: 'float'
        description: 'depth range 60-69'
        versions: ['latest']
      - raw: 'DR_70_79'
        tidy: 'dr_70_79'
        type: 'float'
        description: 'depth range 70-79'
        versions: ['latest']
      - raw: 'DR_80_89'
        tidy: 'dr_80_89'
        type: 'float'
        description: 'depth range 80-89'
        versions: ['latest']
      - raw: 'DR_90_99'
        tidy: 'dr_90_99'
        type: 'float'
        description: 'depth range 90-99'
        versions: ['latest']
      - raw: 'DR_100_149'
        tidy: 'dr_100_149'
        type: 'float'
        description: 'depth range 100-149'
        versions: ['latest']
      - raw: 'DR_150_199'
        tidy: 'dr_150_199'
        type: 'float'
        description: 'depth range 150-199'
        versions: ['latest']
      - raw: 'DR_200_249'
        tidy: 'dr_200_249'
        type: 'float'
        description: 'depth range 200-249'
        versions: ['latest']
      - raw: 'DR_250_299'
        tidy: 'dr_250_299'
        type: 'float'
        description: 'depth range 250-299'
        versions: ['latest']
      - raw: 'DR_300_349'
        tidy: 'dr_300_349'
        type: 'float'
        description: 'depth range 300-349'
        versions: ['latest']
      - raw: 'DR_350_399'
        tidy: 'dr_350_399'
        type: 'float'
        description: 'depth range 350-399'
        versions: ['latest']
      - raw: 'DR_400_449'
        tidy: 'dr_400_449'
        type: 'float'
        description: 'depth range 400-449'
        versions: ['latest']
      - raw: 'DR_450_499'
        tidy: 'dr_450_499'
        type: 'float'
        description: 'depth range 450-499'
        versions: ['latest']
      - raw: 'DR_500_599'
        tidy: 'dr_500_599'
        type: 'float'
        description: 'depth range 500-599'
        versions: ['latest']
      - raw: 'DR_600_699'
        tidy: 'dr_600_699'
        type: 'float'
        description: 'depth range 600-699'
        versions: ['latest']
      - raw: 'DR_700_799'
        tidy: 'dr_700_799'
        type: 'float'
        description: 'depth range 700-799'
        versions: ['latest']
      - raw: 'DR_800_899'
        tidy: 'dr_800_899'
        type: 'float'
        description: 'depth range 800-899'
        versions: ['latest']
      - raw: 'DR_900_999'
        tidy: 'dr_900_999'
        type: 'float'
        description: 'depth range 900-999'
        versions: ['latest']
      - raw: 'DR_1000_1099'
        tidy: 'dr_1000_1099'
        type: 'float'
        description: 'depth range 1000-1099'
        versions: ['latest']
      - raw: 'DR_1100_1199'
        tidy: 'dr_1100_1199'
        type: 'float'
        description: 'depth range 1100-1199'
        versions: ['latest']
      - raw: 'DR_1200_1299'
        tidy: 'dr_1200_1299'
        type: 'float'
        description: 'depth range 1200-1299'
        versions: ['latest']
      - raw: 'DR_1300_1399'
        tidy: 'dr_1300_1399'
        type: 'float'
        description: 'depth range 1300-1399'
        versions: ['latest']
      - raw: 'DR_1400_1499'
        tidy: 'dr_1400_1499'
        type: 'float'
        description: 'depth range 1400-1499'
        versions: ['latest']
      - raw: 'DR_1500_1599'
        tidy: 'dr_1500_1599'
        type: 'float'
        description: 'depth range 1500-1599'
        versions: ['latest']
      - raw: 'DR_1600_1699'
        tidy: 'dr_1600_1699'
        type: 'float'
        description: 'depth range 1600-1699'
        versions: ['latest']
      - raw: 'DR_1700_1799'
        tidy: 'dr_1700_1799'
        type: 'float'
        description: 'depth range 1700-1799'
        versions: ['latest']
      - raw: 'DR_1800_1899'
        tidy: 'dr_1800_1899'
        type: 'float'
        description: 'depth range 1800-1899'
        versions: ['latest']
      - raw: 'DR_1900_1999'
        tidy: 'dr_1900_1999'
        type: 'float'
        description: 'depth range 1900-1999'
        versions: ['latest']
      - raw: 'DR_2000_2999'
        tidy: 'dr_2000_2999'
        type: 'float'
        description: 'depth range 2000-2999'
        versions: ['latest']
      - raw: 'DR_3000_3999'
        tidy: 'dr_3000_3999'
        type: 'float'
        description: 'depth range 3000-3999'
        versions: ['latest']
      - raw: 'DR_4000_4999'
        tidy: 'dr_4000_4999'
        type: 'float'
        description: 'depth range 4000-4999'
        versions: ['latest']
      - raw: 'DR_5000_5999'
        tidy: 'dr_5000_5999'
        type: 'float'
        description: 'depth range 5000-5999'
        versions: ['latest']
      - raw: 'DR_6000_6999'
        tidy: 'dr_6000_6999'
        type: 'float'
        description: 'depth range 6000-6999'
        versions: ['latest']
      - raw: 'DR_7000_7999'
        tidy: 'dr_7000_7999'
        type: 'float'
        description: 'depth range 7000-7999'
        versions: ['latest']
      - raw: 'DR_8000_8999'
        tidy: 'dr_8000_8999'
        type: 'float'
        description: 'depth range 8000-8999'
        versions: ['latest']
      - raw: 'DR_9000_9999'
        tidy: 'dr_9000_9999'
        type: 'float'
        description: 'depth range 9000-9999'
        versions: ['latest']
      - raw: 'DR_10000'
        tidy: 'dr_10000plus'
        type: 'float'
        description: 'depth range 10000+'
        versions: ['latest']
  exoncvg:
    description: 'Exon coverage metrics.'
    pattern: "\\.sage\\.exon\\.medians\\.tsv$"
    ftype: 'txt'
    columns:
      - raw: 'gene'
        tidy: 'gene'
        type: 'char'
        description: 'gene name'
        versions: ['latest']
      - raw: 'chromosome'
        tidy: 'chrom'
        type: 'char'
        description: 'chromosome'
        versions: ['latest']
      - raw: 'posStart'
        tidy: 'start'
        type: 'float'
        description: 'start position'
        versions: ['latest']
      - raw: 'posEnd'
        tidy: 'end'
        type: 'float'
        description: 'end position'
        versions: ['latest']
      - raw: 'exonRank'
        tidy: 'exon'
        type: 'float'
        description: 'exon rank'
        versions: ['latest']
      - raw: 'medianDepth'
        tidy: 'dp_med'
        type: 'float'
        description: 'median depth'
        versions: ['latest']
