tables:
  flagstats:
    description: 'Counts of alignments for each FLAG type.'
    pattern: "\\.flagstat$"
    ftype: 'txt'
    columns:
      - raw: 'passed_or_failed'
        tidy: 'passed_or_failed'
        type: 'char'
        description: 'QC passed or failed'
        versions: ['latest']
      - raw: 'total'
        tidy: 'total'
        type: 'float'
        description: 'total number of reads that are QC pass and fail'
        versions: ['latest']
      - raw: 'primary'
        tidy: 'primary'
        type: 'float'
        description: 'neither secondary nor supplementary'
        versions: ['latest']
      - raw: 'secondary'
        tidy: 'secondary'
        type: 'float'
        description: 'secondary'
        versions: ['latest']
      - raw: 'suppl'
        tidy: 'suppl'
        type: 'float'
        description: 'supplementary'
        versions: ['latest']
      - raw: 'dup'
        tidy: 'dup'
        type: 'float'
        description: 'dup'
        versions: ['latest']
      - raw: 'primary_dup'
        tidy: 'primary_dup'
        type: 'float'
        description: 'dup and neither secondary nor supplementary'
        versions: ['latest']
      - raw: 'mapped'
        tidy: 'mapped'
        type: 'float'
        description: 'not unmap'
        versions: ['latest']
      - raw: 'primary_map'
        tidy: 'primary_map'
        type: 'float'
        description: 'not unmap, not secondary, and not supplementary'
        versions: ['latest']
      - raw: 'paired_in_seq'
        tidy: 'paired_in_seq'
        type: 'float'
        description: 'paired'
        versions: ['latest']
      - raw: 'read1'
        tidy: 'read1'
        type: 'float'
        description: 'both paired and read1'
        versions: ['latest']
      - raw: 'read2'
        tidy: 'read2'
        type: 'float'
        description: 'both paired and read2'
        versions: ['latest']
      - raw: 'proper_pair'
        tidy: 'proper_pair'
        type: 'float'
        description: 'both paired and proper_pair, not unmap'
        versions: ['latest']
      - raw: 'both_map'
        tidy: 'both_map'
        type: 'float'
        description: 'paired and neither unmap nor munmap'
        versions: ['latest']
      - raw: 'singletons'
        tidy: 'singletons'
        type: 'float'
        description: 'both paired and munmap, and not unmap'
        versions: ['latest']
      - raw: 'matemap_diff'
        tidy: 'matemap_diff'
        type: 'float'
        description: 'paired and neither unmap nor munmap, and mrnm not equal to rname'
        versions: ['latest']
      - raw: 'matemap_diff_mapq5'
        tidy: 'matemap_diff_mapq5'
        type: 'float'
        description: 'paired and neither unmap nor munmap, and mrnm not equal to rname, and mapq >= 5'
        versions: ['latest']
      - raw: 'mapped_pct'
        tidy: 'mapped_pct'
        type: 'float'
        description: 'percentage of total reads mapped'
        versions: ['latest']
      - raw: 'primary_map_pct'
        tidy: 'primary_map_pct'
        type: 'float'
        description: 'percentage of total primary reads'
        versions: ['latest']
      - raw: 'proper_pair_pct'
        tidy: 'proper_pair_pct'
        type: 'float'
        description: 'percentage against total pairs'
        versions: ['latest']
      - raw: 'singletons_pct'
        tidy: 'singletons_pct'
        type: 'float'
        description: 'percentage against total pairs'
        versions: ['latest']
