tables:
  gcmed:
    description: 'GC median read depth per GC bucket.'
    pattern: "\\.cobalt\\.gc\\.median\\.tsv$"
    ftype: 'tsv'
    columns:
      - raw: '#gcBucket'
        tidy: 'gc_bucket'
        type: 'char'
        description: 'GC bucket number'
        versions: ['latest']
      - raw: 'median'
        tidy: 'median'
        type: 'float'
        description: 'median read depth in bucket'
        versions: ['latest']
  ratiomed:
    description: 'Chromosome median ratios.'
    pattern: "\\.cobalt\\.ratio\\.median\\.tsv$"
    ftype: 'tsv'
    columns:
      - raw: 'chromosome'
        tidy: 'chrom'
        type: 'char'
        description: 'chromosome'
        versions: ['latest']
      - raw: 'medianRatio'
        tidy: 'median_ratio'
        type: 'float'
        description: 'median ratio'
        versions: ['latest']
      - raw: 'count'
        tidy: 'count'
        type: 'float'
        description: 'count'
        versions: ['latest']
  ratiopcf:
    description: 'Segmented regions determined from the ratios (piecewise constant fit).'
    pattern: "\\.cobalt\\.ratio\\.pcf$"
    ftype: 'tsv'
    columns:
      - raw: 'sampleID'
        tidy: 'sample_id'
        type: 'char'
        description: 'sample ID'
        versions: ['2.0']
      - raw: 'chrom'
        tidy: 'chrom'
        type: 'char'
        description: 'chromosome'
        versions: ['2.0']
      - raw: 'arm'
        tidy: 'arm'
        type: 'char'
        description: 'chromosome arm'
        versions: ['2.0']
      - raw: 'start.pos'
        tidy: 'start'
        type: 'float'
        description: 'start position'
        versions: ['2.0']
      - raw: 'end.pos'
        tidy: 'end'
        type: 'float'
        description: 'end position'
        versions: ['2.0']
      - raw: 'n.probes'
        tidy: 'n_probes'
        type: 'int'
        description: 'number of probes'
        versions: ['2.0']
      - raw: 'mean'
        tidy: 'mean'
        type: 'float'
        description: 'mean'
        versions: ['2.0']
      - raw: 'Chromosome'
        tidy: 'chrom'
        type: 'char'
        description: 'chromosome'
        versions: ['latest']
      - raw: 'Start'
        tidy: 'start'
        type: 'int'
        description: 'start position'
        versions: ['latest']
      - raw: 'End'
        tidy: 'end'
        type: 'int'
        description: 'end position'
        versions: ['latest']
      - raw: 'MeanRatio'
        tidy: 'mean'
        type: 'float'
        description: 'mean ratio'
        versions: ['latest']
  version:
    description: 'Version of the tool.'
    pattern: "^cobalt\\.version$"
    ftype: 'equal-keyvalue'
    columns:
      - raw: 'version'
        tidy: 'version'
        type: 'char'
        description: 'version of the tool'
        versions: ['latest']
      - raw: 'build.date'
        tidy: 'date_build'
        type: 'char'
        description: 'build date'
        versions: ['latest']
