name: pkgdown_env
channels:
  - tidywf/label/dev
  - tidywf
  - conda-forge
dependencies:
  - r-tidywigits ==0.0.7.9008 # bump
  - r-pkgdown
  - r-quarto
  - quarto
  - r-here
  - r-r6toplant
  - plantuml
  - r-htmltools
  - r-reactable
