id: https://example.org/tidywigits/virusbreakend
name: virusbreakend
description: >-
  Viral integration recognition using single breakends.

prefixes:
  linkml: https://w3id.org/linkml/
  virusbreakend: https://example.org/tidywigits/virusbreakend/

imports:
  - linkml:types

default_range: string
default_prefix: virusbreakend

subsets:
  raw:
    description: Raw input file schema
  tidy:
    description: Tidy output schema
  latest:
    description: Virusbreakend latest version

classes:

  #---- Summary ----#
  RawSummary:
    description: VIRUSBreakend analysis summary.
    in_subset: [raw, latest]
    annotations:
      name: summary
      pattern: "\\.virusbreakend\\.vcf\\.summary\\.tsv$"
      ftype: tsv
    attributes:
      taxid_genus:
        range: string
      name_genus:
        range: string
      reads_genus_tree:
        range: integer
      taxid_species:
        range: string
      name_species:
        range: string
      reads_species_tree:
        range: integer
      taxid_assigned:
        range: string
      name_assigned:
        range: string
      reads_assigned_tree:
        range: integer
      reads_assigned_direct:
        range: integer
      reference:
        range: string
      reference_taxid:
        range: string
      reference_kmer_count:
        range: integer
      alternate_kmer_count:
        range: integer
      rname:
        range: string
      startpos:
        range: integer
      endpos:
        range: integer
      numreads:
        range: integer
      covbases:
        range: integer
      coverage:
        range: float
      meandepth:
        range: float
      meanbaseq:
        range: float
      meanmapq:
        range: float
      integrations:
        range: float
      QCStatus:
        range: string

  TidySummary:
    description: VIRUSBreakend analysis summary.
    in_subset: [tidy, latest]
    annotations:
      name: summary
      subtbl: tbl1
    attributes:
      taxid_genus:
        range: string
        description: NCBI taxonomy ID of genus of viral reference
      name_genus:
        range: string
        description: NCBI taxonomy genus name
      reads_genus_tree:
        range: integer
        description: Number of reads assigned to any virus in that genus by kraken2
      taxid_species:
        range: string
        description: NCBI taxonomy ID of species of viral reference
      name_species:
        range: string
        description: NCBI taxonomy species name
      reads_species_tree:
        range: integer
        description: Number of reads assigned to that species (and any sub-species) by kraken2
      taxid_assigned:
        range: string
        description: NCBI taxonomy ID of viral reference
      name_assigned:
        range: string
        description: NCBI taxonomy name of viral reference
      reads_assigned_tree:
        range: integer
        description: Number of reads assigned to the viral reference or taxonomic descendents by kraken2
      reads_assigned_direct:
        range: integer
        description: Number of reads assigned to the viral reference taxid by kraken2
      reference:
        range: string
        description: name of viral reference used.
      reference_taxid:
        range: string
        description: NCBI taxonomy ID of viral reference used. This can be a child taxid of taxid_assigned.
      reference_kmer_count:
        range: integer
        description: count of read kmers matching reference used
      alternate_kmer_count:
        range: integer
        description: count of read kmers matching next best reference candidate
      rname:
        range: string
        description: name of adjusted viral reference
      startpos:
        range: integer
        description: start position of adjusted viral reference. Always 1
      endpos:
        range: integer
        description: end position of adjusted viral reference. Always equal to the viral contig length
      numreads:
        range: integer
        description: Number of reads mapped to adjusted viral reference
      covbases:
        range: integer
        description: Number of bases with at least 1 read mapped
      coverage:
        range: float
        description: Percentage of viral sequence with at least one read mapped
      meandepth:
        range: float
        description: Mean alignment depth
      meanbaseq:
        range: float
        description: Mean base quality of bases mapped to adjusted viral reference
      meanmapq:
        range: float
        description: Mean mapping quality of reads mapped to adjusted viral reference
      integrations:
        range: float
        description: Number of integration breakpoints found.
      qc_status:
        range: string
        description: QC status of viral integration

