# Generated by roxytest: do not edit by hand!

# File R/Peach.R: @testexamples

test_that("Function Peach() @ L22", {
  
  cls <- Peach
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "peach_run1"
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = "peach_.*parquet", full.names = FALSE))
  expect_equal(length(lf), 5)
  qc <- nemo::read_parquet_grep(odir, lf, "peach_qc")
  expect_named(qc, c("input_id", "gene", "status"))
  expect_equal(nrow(qc), 2L)
  hbest <- nemo::read_parquet_grep(odir, lf, "haplotypesbest")
  expect_named(hbest, c("input_id", "gene", "haplotype", "count", "function",
    "linked_drugs", "prescription_urls"))
})

