# Generated by roxytest: do not edit by hand!

# File R/Teal.R: @testexamples

test_that("Function Teal() @ L16", {
  
  cls <- Teal
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "teal_run1"
  obj <- cls$new(indir)
  obj$wrangle(output_dir = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = "teal.*parquet", full.names = FALSE))
  expect_equal(length(lf), 2)
})

