# Generated by roxytest: do not edit by hand!

# File R/Teal.R: @testexamples

test_that("Function Teal() @ L21", {
  
  cls <- Teal; tool <- "teal"
  indir <- system.file("extdata/oa", tool, package = "tidywigits")
  odir <- tempdir()
  id <- paste0(tool, "_run1")
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = paste0(tool, "_.*parquet"), full.names = FALSE))
  expect_equal(length(lf), 2)
  tel <- nemo::read_parquet_grep(odir, lf, "teal_tellength")
  expect_named(tel, c("input_id", "sample_id", "type", "tel_length_raw", "tel_length_final",
    "fragments_full", "fragments_c_rich_partial", "fragments_g_rich_partial",
    "reads_telomeric_total", "purity", "ploidy", "dup_prop", "dp_read_mean", "dp_read_gc50"))
  expect_equal(nrow(tel), 1L)
})

