# Generated by roxytest: do not edit by hand!

# File R/Isofox.R: @testexamples

test_that("Function Isofox() @ L22", {
  
  cls <- Isofox
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "isofox_run1"
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = "isofox_.*parquet", full.names = FALSE))
  expect_equal(length(lf), 8)
  summ <- arrow::read_parquet(file.path(odir, grep("isofox_summary", lf, value = TRUE)))
  expect_named(summ, c("input_id", "sample_id", "qc_status", "frag_tot", "frag_dup",
    "frag_spliced_pct", "frag_unspliced_pct", "frag_alt_pct", "frag_chimeric_pct",
    "spliced_gene_count", "read_length", "frag_length_5th", "frag_length_50th",
    "frag_length_95th", "enriched_gene_pct", "median_gc_ratio", "forward_strand_pct"))
  expect_equal(nrow(summ), 1L)
})

