# Generated by roxytest: do not edit by hand!

# File R/Isofox.R: @testexamples

test_that("Function Isofox() @ L16", {
  
  cls <- Isofox
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "isofox_run1"
  obj <- cls$new(indir)
  obj$nemofy(diro = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = "isofox.*parquet", full.names = FALSE))
  expect_equal(length(lf), 8)
})

