# Generated by roxytest: do not edit by hand!

# File R/Qsee.R: @testexamples

test_that("Function Qsee() @ L23", {
  
  cls <- Qsee; tool <- "qsee"
  indir <- system.file("extdata/oa", tool, package = "tidywigits")
  odir <- tempdir()
  id <- paste0(tool, "_run1")
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = paste0(tool, "_.*parquet"), full.names = FALSE))
  expect_equal(length(lf), 2)
  st <- arrow::read_parquet(file.path(odir, grep("qsee_status", lf, value = TRUE)))
  expect_named(st, c("input_id", "sample_id", "sample_type", "source_tool", "feature_type",
    "feature_name", "feature_value", "qc_status", "fail_condition"))
  vd <- arrow::read_parquet(file.path(odir, grep("qsee_visdata", lf, value = TRUE)))
  expect_named(vd, c("input_id", "sample_id", "sample_type", "source_tool", "feature_type",
    "feature_name", "feature_value", "plot_metadata"))
  expect_equal(length(unique(vd$sample_id)), 2)
})

