# Generated by roxytest: do not edit by hand!

# File R/Virusbreakend.R: @testexamples

test_that("Function Virusbreakend() @ L24", {
  
  cls <- Virusbreakend; tool <- "virusbreakend"
  indir <- system.file("extdata/oa", tool, package = "tidywigits")
  odir <- tempdir()
  id <- paste0(tool, "_run1")
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = paste0(tool, "_.*parquet"), full.names = FALSE))
  expect_equal(length(lf), 1)
  vb <- nemo::read_parquet_grep(odir, lf, "virusbreakend_vcfsummary")
  expect_named(vb, c("input_id", "taxid_genus", "name_genus", "reads_genus_tree",
    "taxid_species", "name_species", "reads_species_tree", "taxid_assigned", "name_assigned",
    "reads_assigned_tree", "reads_assigned_direct", "reference", "reference_taxid",
    "reference_kmer_count", "alternate_kmer_count", "rname", "startpos", "endpos",
    "numreads", "covbases", "coverage", "meandepth", "meanbaseq", "meanmapq",
    "integrations", "qc_status"))
  expect_equal(nrow(vb), 1L)
})

