# Generated by roxytest: do not edit by hand!

# File R/Chord.R: @testexamples

test_that("Function Chord() @ L16", {
  
  cls <- Chord
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "chord_run1"
  obj <- cls$new(indir)
  obj$wrangle(output_dir = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = "chord_.*parquet", full.names = FALSE))
  expect_equal(length(lf), 2)
})

