# Generated by roxytest: do not edit by hand!

# File R/utils.R: @testexamples

test_that("Function refine_by_variant_folder() @ L38", {
  
  files <- tibble::tibble(
    path = c("run1/germline/s1.sage.bqr.tsv", "run1/somatic/s1.sage.bqr.tsv", "run1/s1.bam_metric.gene_coverage.tsv"),
    bname = basename(path),
    prefix = c("s1", "s1", "s1")
  )
  (out <- refine_by_variant_folder(files))
  expect_equal(out$prefix, c("s1_germline", "s1_somatic", "s1"))
  expect_equal(out$bname[1], "s1.germline.sage.bqr.tsv")
  expect_equal(out$bname[3], "s1.bam_metric.gene_coverage.tsv")
})

