# Generated by roxytest: do not edit by hand!

# File R/dvc.R: @testexamples

test_that("Function dvc_download_file() @ L24", {
  
  x <- system.file("extdata/oa/purple/sample1.purple.qc.dvc", package = "tidywigits")
  output_dir <- file.path(tempdir(), "dvc_single_test")
  result <- dvc_download_file(x, output_dir)
  result_cached <- dvc_download_file(x, output_dir, overwrite = FALSE)
  
  expect_true(file.exists(result))
  expect_null(result_cached)
})

