# Generated by roxytest: do not edit by hand!

# File R/Alignments.R: @testexamples

test_that("Function Alignments() @ L22", {
  
  cls <- Alignments; tool <- "alignments"
  indir <- system.file("extdata/oa", tool, package = "tidywigits")
  odir <- tempdir()
  id <- paste0(tool, "_run1")
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = paste0(tool, "_.*parquet"), full.names = FALSE))
  expect_equal(length(lf), 3)
  mdup <- nemo::read_parquet_grep(odir, lf, "markdup")
  expect_named(mdup, c("input_id", "library", "unpaired_reads_examined", "read_pairs_examined",
    "secondary_or_supplementary_reads", "unmapped_reads", "unpaired_read_duplicates",
    "read_pair_duplicates", "read_pair_optical_duplicates", "percent_duplication",
    "estimated_library_size"))
  expect_equal(nrow(mdup), 1L)
})

