# Generated by roxytest: do not edit by hand!

# File R/Cobalt.R: @testexamples

test_that("Function Cobalt() @ L29", {
  
  cls <- Cobalt; tool <- "cobalt"
  indir <- system.file("extdata/oa", tool, package = "tidywigits")
  odir <- tempdir()
  id <- paste0(tool, "_run1")
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = paste0(tool, "_.*parquet"), full.names = FALSE))
  expect_equal(length(lf), 6)
  ver <- nemo::read_parquet_grep(odir, lf, "cobalt_version")
  expect_named(ver, c("input_id", "version", "date_build"))
  expect_equal(nrow(ver), 1L)
  rmed <- nemo::read_parquet_grep(odir, lf, "cobalt_ratiomed")
  expect_named(rmed, c("input_id", "chrom", "median_ratio", "count"))
  gcmed_s <- nemo::read_parquet_grep(odir, lf, "gcmedmain")
  expect_named(gcmed_s, c("input_id", "mean", "median"))
  expect_equal(nrow(gcmed_s), 1L)
  pcfs <- lapply(grep("cobalt_ratiopcf", lf, value = TRUE),
    function(f) names(arrow::read_parquet(file.path(odir, f))))
  pcf_old <- Filter(function(n) "n_probes" %in% n, pcfs)[[1]]
  expect_equal(pcf_old, c("input_id", "sample_id", "chrom", "arm", "start", "end",
    "n_probes", "mean"))
})

