# Generated by roxytest: do not edit by hand!

# File R/Sigs.R: @testexamples

test_that("Function Sigs() @ L18", {
  
  cls <- Sigs
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "sigs_run1"
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = "sigs_.*parquet", full.names = FALSE))
  expect_equal(length(lf), 2)
  alloc <- nemo::read_parquet_grep(odir, lf, "sigs_allocation")
  expect_named(alloc, c("input_id", "signature", "allocation", "percent"))
})

