# Generated by roxytest: do not edit by hand!

# File R/Alignments.R: @testexamples

test_that("Function Alignments() @ L16", {
  
  cls <- Alignments
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "alignments_run1"
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = "alignments_.*parquet", full.names = FALSE))
  expect_equal(length(lf), 3)
})

