# Generated by roxytest: do not edit by hand!

# File R/Chord.R: @testexamples

test_that("Function Chord() @ L20", {
  
  cls <- Chord; tool <- "chord"
  indir <- system.file("extdata/oa", tool, package = "tidywigits")
  odir <- tempdir()
  id <- paste0(tool, "_run1")
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = paste0(tool, "_.*parquet"), full.names = FALSE))
  expect_equal(length(lf), 2)
  pred <- nemo::read_parquet_grep(odir, lf, "chord_prediction")
  expect_named(pred, c("input_id", "sample_id", "p_brca1", "p_brca2", "p_hrd", "hr_status",
    "hrd_type", "remarks_hr_status", "remarks_hrd_type"))
  expect_equal(nrow(pred), 1L)
})

