# Generated by roxytest: do not edit by hand!

# File R/Amber.R: @testexamples

test_that("Function Amber() @ L25", {
  
  cls <- Amber; tool <- "amber"
  indir <- system.file("extdata/oa", tool, package = "tidywigits")
  odir <- tempdir()
  id <- paste0(tool, "_run1")
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = paste0(tool, "_.*parquet"), full.names = FALSE))
  expect_equal(length(lf), 6)
  qc <- nemo::read_parquet_grep(odir, lf, "amber_qc")
  expect_named(qc, c("input_id", "qc_status", "contamination", "consanguinity", "uniparental_disomy"))
  expect_equal(nrow(qc), 1L)
  hom <- nemo::read_parquet_grep(odir, lf, "homozygous")
  expect_named(hom, c("input_id", "chrom", "pos_start", "pos_end", "n_snp", "n_hom", "n_het", "filter"))
  ver <- nemo::read_parquet_grep(odir, lf, "amber_version")
  expect_named(ver, c("input_id", "version", "date_build"))
  bp <- nemo::read_parquet_grep(odir, lf, "^sample1_amber_bafpcf", first = TRUE)
  expect_named(bp, c("input_id", "chrom", "start", "end", "mean_ratio"))
})

