# Generated by roxytest: do not edit by hand!

# File R/Purple.R: @testexamples

test_that("Function Purple() @ L41", {
  
  cls <- Purple; tool <- "purple"
  indir <- system.file("extdata/oa", tool, package = "tidywigits")
  odir <- tempdir()
  id <- paste0(tool, "_run1")
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = paste0(tool, "_.*parquet"), full.names = FALSE))
  expect_equal(length(lf), 19)
  pur <- arrow::read_parquet(file.path(odir, grep("^sample1_purple_puritytsv", lf, value = TRUE)))
  expect_named(pur, c("input_id", "purity", "norm_factor", "fit_score", "diploid_proportion",
    "ploidy", "gender", "status", "polyclonal_proportion", "purity_min", "purity_max",
    "ploidy_min", "ploidy_max", "diploid_proportion_min", "diploid_proportion_max",
    "somatic_penalty", "whole_genome_duplication", "ms_indels_per_mb", "ms_status", "tml",
    "tml_status", "tmb_per_mb", "tmb_status", "tmb_sv", "run_mode", "targeted"))
  expect_equal(nrow(pur), 1L)
  qc <- arrow::read_parquet(file.path(odir, grep("^sample1_purple_qc", lf, value = TRUE)))
  expect_named(qc, c("input_id", "qc_status", "method", "cn_segments", "cn_segments_unsupported",
    "purity", "gender_amber", "gender_cobalt", "deleted_genes", "contamination",
    "germline_aberrations", "mean_depth_amber", "loh_percent", "tinc_level",
    "chimerism_percent"))
  expect_equal(nrow(qc), 1L)
  cnvs <- lapply(grep("purple_cnvgenetsv", lf, value = TRUE),
    function(f) names(arrow::read_parquet(file.path(odir, f))))
  expect_equal(length(cnvs), 3)
  expect_true(any(vapply(cnvs, function(n) "driver_type" %in% n, logical(1))))
  expect_true(any(vapply(cnvs, function(n) !("gc_content" %in% n), logical(1))))
  gad <- arrow::read_parquet(file.path(odir, grep("purple_germampdel", lf, value = TRUE)))
  expect_true(all(c("transcript", "is_partial", "reported_status") %in% names(gad)))
  car <- arrow::read_parquet(file.path(odir, grep("purple_chromarm", lf, value = TRUE)))
  expect_named(car, c("input_id", "chrom", "arm", "cn_mean", "cn_median", "cn_min", "cn_max"))
  dcs <- lapply(grep("germline_purple_drivercatalog|germline_2_purple_drivercatalog", lf, value = TRUE),
    function(f) names(arrow::read_parquet(file.path(odir, f))))
  expect_true(any(vapply(dcs, function(n) "reported_status" %in% n, logical(1))))
})


test_that("Function purple_plot_getter() @ L104", {
  
  x <- tempdir()
  cp_dir <- file.path(tempdir(), "cpdir")
  file.create(file.path(x, paste0("sample1.", c("circos", "copynumber", "map"), ".png")))
  (d1 <- purple_plot_getter(x))
  (d2 <- purple_plot_getter(x, cp_dir))
  expect_equal(nrow(d1), 3)
  expect_equal(ncol(d1), 6)
  expect_equal(ncol(d2), 7)
})

