# Generated by roxytest: do not edit by hand!

# File R/Amber.R: @testexamples

test_that("Function Amber() @ L26", {
  
  cls <- Amber; tool <- "amber"
  indir <- system.file("extdata/oa", tool, package = "tidywigits")
  odir <- tempdir()
  id <- paste0(tool, "_run1")
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = paste0(tool, "_.*parquet"), full.names = FALSE))
  expect_equal(length(lf), 6)
  qc <- arrow::read_parquet(file.path(odir, grep("amber_qc", lf, value = TRUE)))
  expect_named(qc, c("input_id", "qc_status", "contamination", "consanguinity", "uniparental_disomy"))
  expect_equal(nrow(qc), 1L)
  hom <- arrow::read_parquet(file.path(odir, grep("homozygous", lf, value = TRUE)))
  expect_named(hom, c("input_id", "chrom", "pos_start", "pos_end", "n_snp", "n_hom", "n_het", "filter"))
  ver <- arrow::read_parquet(file.path(odir, grep("amber_version", lf, value = TRUE)))
  expect_named(ver, c("input_id", "version", "date_build"))
  bpf <- grep("amber_bafpcf", lf, value = TRUE)
  bp <- arrow::read_parquet(file.path(odir, bpf[!grepl("_2_amber_bafpcf", bpf)]))
  expect_named(bp, c("input_id", "chrom", "start", "end", "mean_ratio"))
})

