# Generated by roxytest: do not edit by hand!

# File R/Neo.R: @testexamples

test_that("Function Neo() @ L24", {
  
  cls <- Neo; tool <- "neo"
  indir <- system.file("extdata/oa", tool, package = "tidywigits")
  odir <- tempdir()
  id <- paste0(tool, "_run1")
  obj <- cls$new(indir)
  obj$run(output_dir = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = paste0(tool, "_.*parquet"), full.names = FALSE))
  expect_equal(length(lf), 4)
  pre <- nemo::read_parquet_grep(odir, lf, "neo_predictions")
  sco <- nemo::read_parquet_grep(odir, lf, "neo_scores")
  fus <- nemo::read_parquet_grep(odir, lf, "neo_isofusions")
  can <- nemo::read_parquet_grep(odir, lf, "neo_candidates")
  expect_true("gene_name" %in% names(pre))
  expect_true("score" %in% names(sco))
  expect_true("fragment_count" %in% names(fus))
  expect_true("variant_type" %in% names(can))
})

