tables:
  blastn:
    description: 'BLASTn hits (pre-v3).'
    pattern: "\\.cider\\.blastn_match\\.tsv\\.gz$"
    ftype: 'tsv'
    columns:
      - raw: 'cdr3Seq'
        tidy: 'cdr3_seq'
        type: 'char'
        description: 'CDR3 nucleotide sequence'
        versions: ['v1.0.0']
      - raw: 'cdr3AA'
        tidy: 'cdr3_aa'
        type: 'char'
        description: 'CDR3 aa sequence'
        versions: ['v1.0.0']
      - raw: 'matchType'
        tidy: 'match_type'
        type: 'char'
        description: 'match type'
        versions: ['v1.0.0']
      - raw: 'gene'
        tidy: 'gene'
        type: 'char'
        description: 'gene name'
        versions: ['v1.0.0']
      - raw: 'functionality'
        tidy: 'functionality'
        type: 'char'
        description: 'functionality'
        versions: ['v1.0.0']
      - raw: 'pIdent'
        tidy: 'p_ident'
        type: 'float'
        description: 'percentage of identical positions'
        versions: ['v1.0.0']
      - raw: 'seqLength'
        tidy: 'seq_length'
        type: 'float'
        description: 'sequence length'
        versions: ['v1.0.0']
      - raw: 'alignStart'
        tidy: 'align_start'
        type: 'float'
        description: 'start of alignment in query'
        versions: ['v1.0.0']
      - raw: 'alignEnd'
        tidy: 'align_end'
        type: 'float'
        description: 'end of alignment in query'
        versions: ['v1.0.0']
      - raw: 'alignGaps'
        tidy: 'align_gaps'
        type: 'float'
        description: 'number of gaps in alignment'
        versions: ['v1.0.0']
      - raw: 'alignEValue'
        tidy: 'align_evalue'
        type: 'float'
        description: 'alignment e-value (lower is better)'
        versions: ['v1.0.0']
      - raw: 'alignBitScore'
        tidy: 'align_bitscore'
        type: 'float'
        description: 'alignment bit score (higher is better)'
        versions: ['v1.0.0']
      - raw: 'refStrand'
        tidy: 'ref_strand'
        type: 'char'
        description: 'reference strand'
        versions: ['v1.0.0']
      - raw: 'refStart'
        tidy: 'ref_start'
        type: 'float'
        description: 'reference start'
        versions: ['v1.0.0']
      - raw: 'refEnd'
        tidy: 'ref_end'
        type: 'float'
        description: 'reference end'
        versions: ['v1.0.0']
      - raw: 'refContig'
        tidy: 'ref_contig'
        type: 'char'
        description: 'reference contig'
        versions: ['v1.0.0']
      - raw: 'refSeq'
        tidy: 'ref_seq'
        type: 'char'
        description: 'reference sequence'
        versions: ['v1.0.0']
  alignmatch:
    description: 'Alignment matches (v3+; replaces blastn).'
    pattern: "\\.cider\\.alignment_match\\.tsv\\.gz$"
    ftype: 'tsv'
    columns:
      - raw: 'cdr3Seq'
        tidy: 'cdr3_seq'
        type: 'char'
        description: 'CDR3 nucleotide sequence'
        versions: ['latest']
      - raw: 'fullSeq'
        tidy: 'full_seq'
        type: 'char'
        description: 'full sequence'
        versions: ['latest']
      - raw: 'matchType'
        tidy: 'match_type'
        type: 'char'
        description: 'match type'
        versions: ['latest']
      - raw: 'gene'
        tidy: 'gene'
        type: 'char'
        description: 'gene name'
        versions: ['latest']
      - raw: 'functionality'
        tidy: 'functionality'
        type: 'char'
        description: 'functionality'
        versions: ['latest']
      - raw: 'layoutAlignStart'
        tidy: 'layout_align_start'
        type: 'float'
        description: 'start of alignment in layout'
        versions: ['latest']
      - raw: 'layoutAlignEnd'
        tidy: 'layout_align_end'
        type: 'float'
        description: 'end of alignment in layout'
        versions: ['latest']
      - raw: 'alignScore'
        tidy: 'align_score'
        type: 'float'
        description: 'alignment score'
        versions: ['latest']
      - raw: 'refContig'
        tidy: 'ref_contig'
        type: 'char'
        description: 'reference contig'
        versions: ['latest']
      - raw: 'refStart'
        tidy: 'ref_start'
        type: 'float'
        description: 'reference start'
        versions: ['latest']
      - raw: 'refEnd'
        tidy: 'ref_end'
        type: 'float'
        description: 'reference end'
        versions: ['latest']
      - raw: 'strand'
        tidy: 'strand'
        type: 'char'
        description: 'strand'
        versions: ['latest']
      - raw: 'refContigLength'
        tidy: 'ref_contig_length'
        type: 'float'
        description: 'reference contig length'
        versions: ['latest']
      - raw: 'cigar'
        tidy: 'cigar'
        type: 'char'
        description: 'CIGAR string'
        versions: ['latest']
      - raw: 'editDistance'
        tidy: 'edit_distance'
        type: 'float'
        description: 'edit distance'
        versions: ['latest']
      - raw: 'querySeqStart'
        tidy: 'query_seq_start'
        type: 'float'
        description: 'start of alignment in query'
        versions: ['latest']
      - raw: 'querySeqEnd'
        tidy: 'query_seq_end'
        type: 'float'
        description: 'end of alignment in query'
        versions: ['latest']
      - raw: 'querySeq'
        tidy: 'query_seq'
        type: 'char'
        description: 'query sequence'
        versions: ['latest']
  locusstats:
    description: 'Locus stats.'
    pattern: "\\.cider\\.locus_stats\\.tsv$"
    ftype: 'tsv'
    columns:
      - raw: 'locus'
        tidy: 'locus'
        type: 'char'
        description: 'Ig/TCR locus'
        versions: ['latest']
      - raw: 'readsUsed'
        tidy: 'reads_used'
        type: 'float'
        description: 'number of reads used to build the VDJ sequences'
        versions: ['latest']
      - raw: 'readsTotal'
        tidy: 'reads_total'
        type: 'float'
        description: 'number of reads found mapped to the locus'
        versions: ['latest']
      - raw: 'downSampled'
        tidy: 'downsampled'
        type: 'char'
        description: 'true if downsampled'
        versions: ['latest']
      - raw: 'sequences'
        tidy: 'sequences'
        type: 'float'
        description: 'number of sequences found'
        versions: ['latest']
      - raw: 'passSequences'
        tidy: 'sequences_pass'
        type: 'float'
        description: 'number of PASS sequences found'
        versions: ['latest']
  vdj:
    description: 'VDJ sequences.'
    pattern: "\\.cider\\.vdj\\.tsv\\.gz$"
    ftype: 'tsv'
    columns:
      - raw: 'cdr3Seq'
        tidy: 'cdr3_seq'
        type: 'char'
        description: 'CDR3 nucleotide sequence'
        versions: ['v1.0.0', 'latest']
      - raw: 'cdr3AA'
        tidy: 'cdr3_aa'
        type: 'char'
        description: 'CDR3 aa sequence'
        versions: ['v1.0.0', 'latest']
      - raw: 'locus'
        tidy: 'locus'
        type: 'char'
        description: 'Ig/TCR locus of the sequence'
        versions: ['v1.0.0', 'latest']
      - raw: 'filter'
        tidy: 'filter'
        type: 'char'
        description: 'PASS if viable CDR3 sequence or one or more filter reasons'
        versions: ['v1.0.0', 'latest']
      - raw: 'blastnStatus'
        tidy: 'blastn_status'
        type: 'char'
        description: 'SKIPPED_BLASTN, V_D_J, V_J, V_D, D_J, V_ONLY, D_ONLY, J_ONLY, NO_REARRANGEMENT, NO_VDJ_ALIGNMENT'
        versions: ['v1.0.0']
      - raw: 'alignmentStatus'
        tidy: 'alignment_status'
        type: 'char'
        description: 'SKIPPED_ALIGNMENT, V_D_J, V_J, V_D, D_J, V_ONLY, D_ONLY, J_ONLY, NO_REARRANGEMENT, NO_VDJ_ALIGNMENT'
        versions: ['latest']
      - raw: 'minHighQualBaseReads'
        tidy: 'min_high_qual_base_reads'
        type: 'float'
        description: 'number of reads in the least supported base in the CDR3 region'
        versions: ['v1.0.0', 'latest']
      - raw: 'assignedReads'
        tidy: 'assigned_reads'
        type: 'float'
        description: 'total reads assigned to candidate sequence'
        versions: ['v1.0.0', 'latest']
      - raw: 'vAlignedReads'
        tidy: 'v_aligned_reads'
        type: 'float'
        description: 'number of reads initially aligned to V gene'
        versions: ['v1.0.0', 'latest']
      - raw: 'jAlignedReads'
        tidy: 'j_aligned_reads'
        type: 'float'
        description: 'number of reads initially aligned to J gene'
        versions: ['v1.0.0', 'latest']
      - raw: 'inFrame'
        tidy: 'in_frame'
        type: 'char'
        description: 'CDR3 sequence is inframe'
        versions: ['v1.0.0', 'latest']
      - raw: 'containsStop'
        tidy: 'contains_stop'
        type: 'char'
        description: 'CDR3 contains stop codon'
        versions: ['v1.0.0', 'latest']
      - raw: 'vType'
        tidy: 'v_type'
        type: 'char'
        description: '{IGKV;IGLV;IGHV;TRAV;TRBV;TRDV;TRGV}'
        versions: ['v1.0.0', 'latest']
      - raw: 'vAnchorStart'
        tidy: 'v_anchor_start'
        type: 'float'
        description: 'position of V anchor start in nt sequence'
        versions: ['v1.0.0', 'latest']
      - raw: 'vAnchorEnd'
        tidy: 'v_anchor_end'
        type: 'float'
        description: 'position of V anchor end in nt sequence'
        versions: ['v1.0.0', 'latest']
      - raw: 'vAnchorSeq'
        tidy: 'v_anchor_seq'
        type: 'char'
        description: 'V anchor sequence in nt'
        versions: ['v1.0.0', 'latest']
      - raw: 'vAnchorTemplateSeq'
        tidy: 'v_anchor_template_seq'
        type: 'char'
        description: 'best scoring V template anchor in nt'
        versions: ['v1.0.0', 'latest']
      - raw: 'vAnchorAA'
        tidy: 'v_anchor_aa'
        type: 'char'
        description: 'V anchor sequence in AA'
        versions: ['v1.0.0', 'latest']
      - raw: 'vAnchorTemplateAA'
        tidy: 'v_anchor_template_aa'
        type: 'char'
        description: 'best scoring V template Anchor in AA'
        versions: ['v1.0.0', 'latest']
      - raw: 'vMatchMethod'
        tidy: 'v_match_method'
        type: 'char'
        description: 'V match method'
        versions: ['v1.0.0', 'latest']
      - raw: 'vSimilarityScore'
        tidy: 'v_similarity_score'
        type: 'float'
        description: 'blosum similarity score for template anchor'
        versions: ['v1.0.0', 'latest']
      - raw: 'vNonSplitReads'
        tidy: 'v_non_split_reads'
        type: 'float'
        description: 'count of reads supporting sequence with at least 30 aligned bases either side of last base of conserved C'
        versions: ['v1.0.0', 'latest']
      - raw: 'jType'
        tidy: 'j_type'
        type: 'char'
        description: '{IGHJ;IGKJ;IGK-KDE,IGLJ;TRAJ;TRBJ;TRDJ;TRGJ}'
        versions: ['v1.0.0', 'latest']
      - raw: 'jAnchorStart'
        tidy: 'j_anchor_start'
        type: 'float'
        description: 'position of J anchor start in nt sequence'
        versions: ['v1.0.0', 'latest']
      - raw: 'jAnchorEnd'
        tidy: 'j_anchor_end'
        type: 'float'
        description: 'position of J anchor end in nt sequence'
        versions: ['v1.0.0', 'latest']
      - raw: 'jAnchorSeq'
        tidy: 'j_anchor_seq'
        type: 'char'
        description: 'J anchor sequence in nt'
        versions: ['v1.0.0', 'latest']
      - raw: 'jAnchorTemplateSeq'
        tidy: 'j_anchor_template_seq'
        type: 'char'
        description: 'best scoring J template anchor in nt'
        versions: ['v1.0.0', 'latest']
      - raw: 'jAnchorAA'
        tidy: 'j_anchor_aa'
        type: 'char'
        description: 'J anchor sequence in AA'
        versions: ['v1.0.0', 'latest']
      - raw: 'jAnchorTemplateAA'
        tidy: 'j_anchor_template_aa'
        type: 'char'
        description: 'best scoring J template Anchor in AA'
        versions: ['v1.0.0', 'latest']
      - raw: 'jMatchMethod'
        tidy: 'j_match_method'
        type: 'char'
        description: 'J match method'
        versions: ['v1.0.0', 'latest']
      - raw: 'jSimilarityScore'
        tidy: 'j_similarity_score'
        type: 'float'
        description: 'Blosum62 similarity score for template anchor'
        versions: ['v1.0.0', 'latest']
      - raw: 'jNonSplitReads'
        tidy: 'j_non_split_reads'
        type: 'float'
        description: 'count of reads supporting sequence with at least 30 aligned bases either side of first base of conserved W/F'
        versions: ['v1.0.0', 'latest']
      - raw: 'vGene'
        tidy: 'v_gene'
        type: 'char'
        description: 'the V gene allele that this sequence is aligned to'
        versions: ['v1.0.0', 'latest']
      - raw: 'vGeneSupplementary'
        tidy: 'v_gene_supplementary'
        type: 'char'
        description: 'supplementary V gene alleles'
        versions: ['latest']
      - raw: 'vPIdent'
        tidy: 'v_pident'
        type: 'float'
        description: 'the align sequence % identity with the V gene'
        versions: ['v1.0.0', 'latest']
      - raw: 'vPIdentLen'
        tidy: 'v_pident_len'
        type: 'float'
        description: 'length over which V gene % identity is computed'
        versions: ['latest']
      - raw: 'vPIdentIndelBases'
        tidy: 'v_pident_indel_bases'
        type: 'float'
        description: 'number of indel bases in the V gene alignment'
        versions: ['latest']
      - raw: 'vPIdentClipBases'
        tidy: 'v_pident_clip_bases'
        type: 'float'
        description: 'number of clipped bases in the V gene alignment'
        versions: ['latest']
      - raw: 'SHMStatus'
        tidy: 'shm_status'
        type: 'char'
        description: 'somatic hypermutation status'
        versions: ['latest']
      - raw: 'vAlignStart'
        tidy: 'v_align_start'
        type: 'float'
        description: 'start of the alignment with the V gene'
        versions: ['v1.0.0', 'latest']
      - raw: 'vAlignEnd'
        tidy: 'v_align_end'
        type: 'float'
        description: 'end of the alignment with the V gene'
        versions: ['v1.0.0', 'latest']
      - raw: 'dGene'
        tidy: 'd_gene'
        type: 'char'
        description: 'the D gene allele that this sequence is aligned to'
        versions: ['v1.0.0', 'latest']
      - raw: 'dGeneSupplementary'
        tidy: 'd_gene_supplementary'
        type: 'char'
        description: 'supplementary D gene alleles'
        versions: ['latest']
      - raw: 'dPIdent'
        tidy: 'd_pident'
        type: 'float'
        description: 'the align sequence % identity with the D gene'
        versions: ['v1.0.0']
      - raw: 'dAlignStart'
        tidy: 'd_align_start'
        type: 'float'
        description: 'start of the alignment with the D gene'
        versions: ['v1.0.0', 'latest']
      - raw: 'dAlignEnd'
        tidy: 'd_align_end'
        type: 'float'
        description: 'end of the alignment with the D gene'
        versions: ['v1.0.0', 'latest']
      - raw: 'jGene'
        tidy: 'j_gene'
        type: 'char'
        description: 'the J gene allele that this sequence is aligned to'
        versions: ['v1.0.0', 'latest']
      - raw: 'jGeneSupplementary'
        tidy: 'j_gene_supplementary'
        type: 'char'
        description: 'supplementary J gene alleles'
        versions: ['latest']
      - raw: 'jPIdent'
        tidy: 'j_pident'
        type: 'float'
        description: 'the align sequence % identity with the J gene'
        versions: ['v1.0.0', 'latest']
      - raw: 'jPIdentLen'
        tidy: 'j_pident_len'
        type: 'float'
        description: 'length over which J gene % identity is computed'
        versions: ['latest']
      - raw: 'jPIdentIndelBases'
        tidy: 'j_pident_indel_bases'
        type: 'float'
        description: 'number of indel bases in the J gene alignment'
        versions: ['latest']
      - raw: 'jPIdentClipBases'
        tidy: 'j_pident_clip_bases'
        type: 'float'
        description: 'number of clipped bases in the J gene alignment'
        versions: ['latest']
      - raw: 'jAlignStart'
        tidy: 'j_align_start'
        type: 'float'
        description: 'start of the alignment with the J gene'
        versions: ['v1.0.0', 'latest']
      - raw: 'jAlignEnd'
        tidy: 'j_align_end'
        type: 'float'
        description: 'end of the alignment with the J gene'
        versions: ['v1.0.0', 'latest']
      - raw: 'vPrimerMatches'
        tidy: 'v_primer_matches'
        type: 'float'
        description: 'V primer matches'
        versions: ['v1.0.0', 'latest']
      - raw: 'jPrimerMatches'
        tidy: 'j_primer_matches'
        type: 'float'
        description: 'J primer matches'
        versions: ['v1.0.0', 'latest']
      - raw: 'layoutId'
        tidy: 'layout_id'
        type: 'char'
        description: 'layout ID'
        versions: ['v1.0.0', 'latest']
      - raw: 'fullSeq'
        tidy: 'full_seq'
        type: 'char'
        description: 'full consensus sequence in nucleotides'
        versions: ['v1.0.0', 'latest']
      - raw: 'support'
        tidy: 'support'
        type: 'char'
        description: 'counts of high quality base support at each nucleotide (radix-36 ASCII encoded)'
        versions: ['v1.0.0', 'latest']
