tables:
  coverage:
    description: 'Per-base coverage counts.'
    pattern: "\\.bam_metric\\.coverage\\.tsv$"
    ftype: 'txt'
    columns:
      - raw: 'Coverage'
        tidy: 'coverage'
        type: 'float'
        description: 'coverage depth'
        versions: ['latest']
      - raw: 'Count'
        tidy: 'count'
        type: 'float'
        description: 'count of bases at this coverage'
        versions: ['latest']
  fraglength:
    description: 'Fragment length counts.'
    pattern: "\\.bam_metric\\.frag_length\\.tsv$"
    ftype: 'txt'
    columns:
      - raw: 'FragmentLength'
        tidy: 'length'
        type: 'char'
        description: 'fragment length'
        versions: ['latest']
      - raw: 'Count'
        tidy: 'count'
        type: 'float'
        description: 'count of fragments at this length'
        versions: ['latest']
  partitionstats:
    description: 'Per-partition alignment stats.'
    pattern: "\\.bam_metric\\.partition_stats\\.tsv$"
    ftype: 'txt'
    columns:
      - raw: 'Chromosome'
        tidy: 'chrom'
        type: 'char'
        description: 'chromosome'
        versions: ['latest']
      - raw: 'PositionStart'
        tidy: 'pos_start'
        type: 'float'
        description: 'start position'
        versions: ['latest']
      - raw: 'PositionEnd'
        tidy: 'pos_end'
        type: 'float'
        description: 'end position'
        versions: ['latest']
      - raw: 'TotalReads'
        tidy: 'total_reads'
        type: 'float'
        description: 'total reads'
        versions: ['latest']
      - raw: 'DuplicateReads'
        tidy: 'dup_reads'
        type: 'float'
        description: 'duplicate reads'
        versions: ['latest']
      - raw: 'ChimericReads'
        tidy: 'chim_reads'
        type: 'float'
        description: 'chimeric reads'
        versions: ['latest']
      - raw: 'InterPartition'
        tidy: 'interpartition'
        type: 'float'
        description: 'inter-partition reads'
        versions: ['latest']
      - raw: 'UnmappedReads'
        tidy: 'unmap_reads'
        type: 'float'
        description: 'unmapped reads'
        versions: ['latest']
      - raw: 'ProcessTime'
        tidy: 'process_time'
        type: 'float'
        description: 'process time'
        versions: ['latest']
  flagstats:
    description: 'Counts of alignments for each FLAG type.'
    pattern: "\\.bam_metric\\.flag_counts\\.tsv$|\\.flagstat$"
    ftype: 'txt'
    columns:
      - raw: 'passed_or_failed'
        tidy: 'passed_or_failed'
        type: 'char'
        description: 'QC passed or failed'
        versions: ['latest']
      - raw: 'total'
        tidy: 'total'
        type: 'float'
        description: 'total number of reads that are QC pass and fail'
        versions: ['latest']
      - raw: 'primary'
        tidy: 'primary'
        type: 'float'
        description: 'neither secondary nor supplementary'
        versions: ['latest']
      - raw: 'secondary'
        tidy: 'secondary'
        type: 'float'
        description: 'secondary'
        versions: ['latest']
      - raw: 'suppl'
        tidy: 'suppl'
        type: 'float'
        description: 'supplementary'
        versions: ['latest']
      - raw: 'dup'
        tidy: 'dup'
        type: 'float'
        description: 'dup'
        versions: ['latest']
      - raw: 'primary_dup'
        tidy: 'primary_dup'
        type: 'float'
        description: 'dup and neither secondary nor supplementary'
        versions: ['latest']
      - raw: 'mapped'
        tidy: 'mapped'
        type: 'float'
        description: 'not unmap'
        versions: ['latest']
      - raw: 'primary_map'
        tidy: 'primary_map'
        type: 'float'
        description: 'not unmap, not secondary, and not supplementary'
        versions: ['latest']
      - raw: 'paired_in_seq'
        tidy: 'paired_in_seq'
        type: 'float'
        description: 'paired'
        versions: ['latest']
      - raw: 'read1'
        tidy: 'read1'
        type: 'float'
        description: 'both paired and read1'
        versions: ['latest']
      - raw: 'read2'
        tidy: 'read2'
        type: 'float'
        description: 'both paired and read2'
        versions: ['latest']
      - raw: 'proper_pair'
        tidy: 'proper_pair'
        type: 'float'
        description: 'both paired and proper_pair, not unmap'
        versions: ['latest']
      - raw: 'both_map'
        tidy: 'both_map'
        type: 'float'
        description: 'paired and neither unmap nor munmap'
        versions: ['latest']
      - raw: 'singletons'
        tidy: 'singletons'
        type: 'float'
        description: 'both paired and munmap, and not unmap'
        versions: ['latest']
      - raw: 'matemap_diff'
        tidy: 'matemap_diff'
        type: 'float'
        description: 'paired and neither unmap nor munmap, and mrnm not equal to rname'
        versions: ['latest']
      - raw: 'matemap_diff_mapq5'
        tidy: 'matemap_diff_mapq5'
        type: 'float'
        description: 'paired and neither unmap nor munmap, and mrnm not equal to rname, and mapq >= 5'
        versions: ['latest']
      - raw: 'mapped_pct'
        tidy: 'mapped_pct'
        type: 'float'
        description: 'percentage of total reads mapped'
        versions: ['latest']
      - raw: 'primary_map_pct'
        tidy: 'primary_map_pct'
        type: 'float'
        description: 'percentage of total primary reads'
        versions: ['latest']
      - raw: 'proper_pair_pct'
        tidy: 'proper_pair_pct'
        type: 'float'
        description: 'percentage against total pairs'
        versions: ['latest']
      - raw: 'singletons_pct'
        tidy: 'singletons_pct'
        type: 'float'
        description: 'percentage against total pairs'
        versions: ['latest']
  exoncvg:
    description: 'Exon median depth.'
    pattern: "\\.bam_metric\\.exon_medians\\.tsv$"
    ftype: 'txt'
    columns:
      - raw: 'gene'
        tidy: 'gene'
        type: 'char'
        description: 'gene name'
        versions: ['latest']
      - raw: 'chromosome'
        tidy: 'chrom'
        type: 'char'
        description: 'chromosome'
        versions: ['latest']
      - raw: 'posStart'
        tidy: 'start'
        type: 'float'
        description: 'start position'
        versions: ['latest']
      - raw: 'posEnd'
        tidy: 'end'
        type: 'float'
        description: 'end position'
        versions: ['latest']
      - raw: 'exonRank'
        tidy: 'exon'
        type: 'float'
        description: 'exon rank'
        versions: ['latest']
      - raw: 'medianDepth'
        tidy: 'dp_med'
        type: 'float'
        description: 'median depth'
        versions: ['latest']
