name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version (e.g. 0.1.0)'
        required: true
        type: string

jobs:
  bump:
    uses: tidywf/.github/.github/workflows/bump.yaml@main
    permissions:
      contents: write
    with:
      pkg_name: tidywigits
      pkg_version: ${{ inputs.version }}
      dvc: true
    secrets: inherit
